-- Créer la base de données
CREATE DATABASE IF NOT EXISTS potefolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE potefolio;

-- Projets
CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  long_description TEXT NOT NULL,
  problem TEXT NOT NULL,
  solution TEXT NOT NULL,
  key_features TEXT NOT NULL,
  results TEXT NOT NULL,
  challenges TEXT NOT NULL,
  technologies TEXT NOT NULL,
  category VARCHAR(100) NOT NULL,
  image VARCHAR(500) NOT NULL DEFAULT '',
  gallery TEXT NOT NULL DEFAULT '[]',
  github_url VARCHAR(500),
  demo_url VARCHAR(500),
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  date DATETIME NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'published',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Compétences
CREATE TABLE IF NOT EXISTS skills (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  level INT NOT NULL,
  icon VARCHAR(255) NOT NULL DEFAULT '',
  category VARCHAR(100) NOT NULL,
  description TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Expériences
CREATE TABLE IF NOT EXISTS experiences (
  id VARCHAR(36) PRIMARY KEY,
  company VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME,
  current BOOLEAN NOT NULL DEFAULT FALSE,
  description TEXT NOT NULL,
  achievements TEXT NOT NULL DEFAULT '[]',
  company_logo VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Éducation
CREATE TABLE IF NOT EXISTS education (
  id VARCHAR(36) PRIMARY KEY,
  institution VARCHAR(255) NOT NULL,
  degree VARCHAR(255) NOT NULL,
  field VARCHAR(255) NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME,
  current BOOLEAN NOT NULL DEFAULT FALSE,
  description TEXT NOT NULL,
  highlights TEXT NOT NULL DEFAULT '[]',
  logo VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Certifications
CREATE TABLE IF NOT EXISTS certifications (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  issuer VARCHAR(255) NOT NULL,
  date DATETIME NOT NULL,
  expiry_date DATETIME,
  credential_url VARCHAR(500),
  badge VARCHAR(500) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Témoignages
CREATE TABLE IF NOT EXISTS testimonials (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  company VARCHAR(255) NOT NULL,
  avatar VARCHAR(500) NOT NULL DEFAULT '',
  content TEXT NOT NULL,
  rating INT NOT NULL DEFAULT 5,
  date DATETIME NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  validated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Articles de blog
CREATE TABLE IF NOT EXISTS blog_posts (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  cover_image VARCHAR(500) NOT NULL DEFAULT '',
  category VARCHAR(100) NOT NULL,
  tags TEXT NOT NULL DEFAULT '[]',
  author VARCHAR(255) NOT NULL,
  author_avatar VARCHAR(500) NOT NULL DEFAULT '',
  date DATETIME NOT NULL,
  read_time INT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  scheduled_date DATETIME,
  popular BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Commentaires de blog
CREATE TABLE IF NOT EXISTS blog_comments (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  date DATETIME NOT NULL,
  validated BOOLEAN NOT NULL DEFAULT FALSE,
  post_id VARCHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES blog_posts(id) ON DELETE CASCADE
);

-- Services
CREATE TABLE IF NOT EXISTS services (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  long_description TEXT NOT NULL,
  icon VARCHAR(100) NOT NULL DEFAULT '',
  features TEXT NOT NULL DEFAULT '[]',
  price VARCHAR(100),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- FAQ
CREATE TABLE IF NOT EXISTS faq (
  id VARCHAR(36) PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category VARCHAR(100) NOT NULL,
  ordr INT NOT NULL DEFAULT 0
);

-- Messages de contact
CREATE TABLE IF NOT EXISTS contact_messages (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  subject VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  date DATETIME NOT NULL,
  `read` BOOLEAN NOT NULL DEFAULT FALSE,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  replied BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Événements et formations
CREATE TABLE IF NOT EXISTS event_trainings (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  long_description TEXT NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME,
  location VARCHAR(255) NOT NULL,
  organizer VARCHAR(255) NOT NULL,
  organizer_url VARCHAR(500),
  image VARCHAR(500),
  gallery TEXT NOT NULL DEFAULT '[]',
  tags TEXT NOT NULL DEFAULT '[]',
  certificate BOOLEAN NOT NULL DEFAULT FALSE,
  certificate_url VARCHAR(500),
  registration_url VARCHAR(500),
  speaker VARCHAR(255),
  speaker_bio TEXT,
  skills TEXT NOT NULL DEFAULT '[]',
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(50) NOT NULL DEFAULT 'upcoming',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Utilisateurs admin
CREATE TABLE IF NOT EXISTS admin_users (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL DEFAULT '',
  avatar VARCHAR(500) NOT NULL DEFAULT '',
  role VARCHAR(50) NOT NULL DEFAULT 'editor',
  permissions TEXT NOT NULL DEFAULT '[]',
  two_factor_enabled TINYINT(1) NOT NULL DEFAULT 0,
  two_factor_secret VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Configuration du site
CREATE TABLE IF NOT EXISTS site_configs (
  id VARCHAR(36) PRIMARY KEY,
  cle VARCHAR(255) NOT NULL UNIQUE,
  valeur TEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Messages du chat
CREATE TABLE IF NOT EXISTS chat_messages (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  timestamp DATETIME NOT NULL,
  src VARCHAR(50) NOT NULL DEFAULT 'client',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Conversations du chatbot
CREATE TABLE IF NOT EXISTS chatbot_conversations (
  id VARCHAR(36) PRIMARY KEY,
  session_id VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_session (session_id)
);
